### ISSUE TITLE
Change default build directory

### ISSUE THREAD

**Issue by tlvince** [pbrisbin/raury#1]
Running `raury` without the `--build-dir` option yields a nice surprise of cluttering up `$HOME`, especially with `-Syu`.

Saner default build directory candidates could include `/tmp/raury` or `${XDG_CACHE_HOME:-$HOME/.cache}/raury`.

**Comment by pbrisbin** [comment]
This is a valid point. The only thing is, my hope for a spartan codebase telling me I don't want to add logic to check / create if not present when it comes to the build directory. I also don't want a user using the defaults to have to `mkdir` something manually.

This left me with `/tmp`, `./`, or `~/` as sane choices. To be fair, the "clutter" is not unreasonable, being limited to a single directory per package being built.

I'm not sure what I'll do yet.

**Comment by pbrisbin** [comment]
Also note, the build directory (as well as any option) can be set permanently in the config file -- something I should make more clear (or present at all ;) in the README.

**Comment by tlvince** [comment]
Ah, perfect. I wasn't aware there was a config file (and my comment was made in haste). Cheers!
