### ISSUE TITLE
Upgrading development packages

### ISSUE THREAD

**Issue by tlvince** [pbrisbin/raury#2]
Is upgrading development packages (`-git`, `-svn` etc.) handled by `raury`?

Such packages aren't listed in `raury -Syu` and there doesn't seem to be an
alternative to `aurget --devel`, although there is the following line with the
`--debug` option:

```
development_regex: (?-mix:-(git|hg|svn|darcs|cvs|bzr)$)
```

**Comment by pbrisbin** [comment]
Yeah, adding --devel is on my TODO list -- I don't remember if or how much
of it I've coded...

You can set the regex to something that will never match (in your config)
to prevent this behavior for now if you'd like.
